name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get install gcc

    - name: Compile C program
      run: gcc -o rectangle_perimeter rectangle_perimeter.c

    - name: Run program with input from keyboard
      run: |
        test_cases=(
          "5 10 30"
          "2 8 20"
          "3 5 16"
          "7 7 28"
          "0 0 0"
        )
        
        for test_case in "${test_cases[@]}"; do
          IFS=' ' read -r height width expected_output <<< "$test_case"
          output=$(echo "$height $width" | ./rectangle_perimeter)
          if [ "$output" = "$expected_output" ]; then
            echo "Test case ($height x $width) passed"
          else
            echo "Test case ($height x $width) failed"
            exit 1
          fi
        done
