name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get install gcc

    - name: Compile and run C program
      run: gcc -o main main.c && ./main

    - name: Verify output
      run: |
        if [ "$(./main)" = "Xin chào các bạn" ]; then
          echo "Output is correct"
          exit 0
        else
          echo "Output is incorrect"
          exit 1
        fi
