name: Check main.c

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Check main.c
      run: |
        if grep -q "Xin chào" main.c; then
          echo "Test passed: 'Xin chào' found in main.c"
          exit 0
        else
          echo "Test failed: 'Xin chào' not found in main.c"
          exit 1
        fi
