name: C Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up C environment
      uses: actions/setup-cxx@v2

    - name: Build the program
      run: gcc -o rectangle rectangle.c

    - name: Run tests
      run: |
        ./rectangle << EOF
        5
        7
        EOF
